# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 072eee377528170c06fc64efb9505aaec5d04c14c4a0fa5723916769487fc8034c2d34879909eb673d00c127fa37a6f5d38f5071246742b23c34c75996d3b456

test:
  secret_key_base: 31b4210c1df4e1231c80651720f322d50274be8c12c88cc6b9a4c7fd9b1d20b20b2f3fd26f19f32cebb42a1b7d2595358258f27e33161323ce3b23a4be5cf13c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
